In [1]:
from sklearn.datasets import load_iris

# 1. import datasets
iris = load_iris()

print (iris.feature_names)
print (iris.target_names)
print (iris.data[0])
print( iris.target[0])

for i in range(len(iris.target)):
    print ("Example %d : lebel : %s, features : %s" % (i, iris.target[i], iris.data[i]))


['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[5.1 3.5 1.4 0.2]
0
Example 0 : lebel : 0, features : [5.1 3.5 1.4 0.2]
Example 1 : lebel : 0, features : [4.9 3.  1.4 0.2]
Example 2 : lebel : 0, features : [4.7 3.2 1.3 0.2]
Example 3 : lebel : 0, features : [4.6 3.1 1.5 0.2]
Example 4 : lebel : 0, features : [5.  3.6 1.4 0.2]
Example 5 : lebel : 0, features : [5.4 3.9 1.7 0.4]
Example 6 : lebel : 0, features : [4.6 3.4 1.4 0.3]
Example 7 : lebel : 0, features : [5.  3.4 1.5 0.2]
Example 8 : lebel : 0, features : [4.4 2.9 1.4 0.2]
Example 9 : lebel : 0, features : [4.9 3.1 1.5 0.1]
Example 10 : lebel : 0, features : [5.4 3.7 1.5 0.2]
Example 11 : lebel : 0, features : [4.8 3.4 1.6 0.2]
Example 12 : lebel : 0, features : [4.8 3.  1.4 0.1]
Example 13 : lebel : 0, features : [4.3 3.  1.1 0.1]
Example 14 : lebel : 0, features : [5.8 4.  1.2 0.2]
Example 15 : lebel : 0, features : [5.7 4.4 1.5 0.4]
Example 16 : lebel : 0,

In [2]:
# 2. Train classifier
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree

test_idx = [0, 50, 100]

# training data
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

# testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

In [3]:
# 3. Predict label for new flower
clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

print (test_target)
print (clf.predict(test_data))

[0 1 2]
[0 1 2]


In [22]:
# 4. Visualize for tree
import pydot
import graphviz
from io import StringIO
from IPython.display import Image

dot_data = StringIO()
tree.export_graphviz(clf,
                        out_file=dot_data,
                        feature_names=iris.feature_names,
                        class_names=iris.target_names,
                        filled=True, rounded=True,
                        impurity=False)
graph = pydot.graph_from_dot_data(dot_data.getvalue())
graphviz.Source(graph)
# Image(graph[0].create_png())

ExecutableNotFound: failed to execute ['dot', '-Tsvg'], make sure the Graphviz executables are on your systems' PATH